[package]
name = "claims"
version = "0.1.0"
edition = "2021"

[dependencies]
vdb = { path = "../vdb" }

# Serialization
serde = { workspace = true }
bincode = { workspace = true }

# Utilities
blake3 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
